[package]
name = "tokio-core"
version = "0.1.17"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-core"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-core/0.1"
description = """
Core I/O and event loop primitives for asynchronous I/O in Rust. Foundation for
the rest of the tokio crates.
"""
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "tokio-rs/tokio-core" }
appveyor = { repository = "alexcrichton/tokio-core" }

[dependencies]
bytes = "0.4"
log = "0.4"
mio = { git = "https://gitlab.redox-os.org/redox-os/mio" }
scoped-tls = "0.1.0"
iovec = "0.1.2"
tokio-io = { git = "https://gitlab.redox-os.org/redox-os/tokio" }
tokio = { git = "https://gitlab.redox-os.org/redox-os/tokio" }
tokio-executor = { git = "https://gitlab.redox-os.org/redox-os/tokio" }
tokio-reactor = { git = "https://gitlab.redox-os.org/redox-os/tokio" }
tokio-timer = { git = "https://gitlab.redox-os.org/redox-os/tokio" }
futures = "0.1.21"

[dev-dependencies]
env_logger = { version = "0.4", default-features = false }
flate2 = { version = "1", features = ["tokio"] }
futures-cpupool = "0.1"
http = "0.1"
httparse = "1.0"
libc = "0.2"
num_cpus = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
